<% branch = Git.open(".").current_branch %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: movie_game_development-<%= branch %>

test:
  <<: *default
  database: movie_game_test-<%= branch %>

production:
  <<: *default
  database: movie_game_development-<%= branch %>
