

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: movie_game_development

test:
  <<: *default
  database: movie_game_test

production:
  <<: *default
  database: movie_game_production

# Before deploying to Heroku, remove branch stuff